import {ParagraphType} from '../article.js';
export class A2 { static get() {
const a2 = 
{ title: 'Quailing qualia',
  date: '2019/08/21',
  author: 'M. S',
  thumb: 'assets/img/craft/recursion.jpg',
  body: [

    {type: ParagraphType.Paragraph, content: 'Edit (2024/11) — rereading this five years after having written it makes me question whether I should share anything at all on this blog. I’m not really sure that I wasn’t entirely rambling at the time. Some of the links are interesting, though, and I suppose I still need to keep some of my past existential musings in one place. There were a few other articles like this one that I decided to throw away, but I don’t really feel like removing this one.' },
    {type: ParagraphType.Title, content: 'I. Subjective consciousness and qualia' },
    {type: ParagraphType.Paragraph, content: 'Though the question of consciousness has been largely discussed in the past, notably by [<a href="https://en.wikipedia.org/wiki/John_Locke#The_human_mind">Locke</a>], some of its aspects have gained modern interest since an article published by [<a href="https://en.wikipedia.org/wiki/What_Is_it_Like_to_Be_a_Bat%3F">Nagel 1974</a>].' },
    {type: ParagraphType.Paragraph, content: 'In this article, Nagel suggests that there is a fundamental difference between experiencing a mental state from the first person, and describing this mental state from an external perspective. In other words, an experience lived at the first person would carry a subjective aspect which is not reducible to a physiological phenomenon. This subjective aspect would evade an objective, external description. Notable examples include the perception of colors (how do you know your “blue” is not the same as someone else’s “orange”?), but never point out exactly what is limiting in a physiological description.' },
    {type: ParagraphType.Paragraph, content: 'The hypothetical subjective core of consciousness is often called a “quale”—plural qualia. The problem of their possible existence and nature have been the object of thorough inquiry in recent literature, since the articles by [Nagel 1974, <a href="https://www.goodreads.com/book/show/18720319-epiphenomenal-qualia">Jackson 1982</a>], leading to the definition of a “hard problem of consciousness.”' },
    
    {type: ParagraphType.Title, content: 'II. Proponents and opponents' },
    {type: ParagraphType.Paragraph, content: 'Many philosophers are convinced of the existence of qualia, the most prominent being Chalmers. One can also note [Levine, Lowe, Maund, Perkins, Ramachandran-Hirstein, Robinson, Wright—@<a href="https://en.wikipedia.org/wiki/Qualia">wiki</a>]. Some famous scientists subscribe to their point of view [Schrödinger]. The arguments in favor of the existence of qualia are not very strong, which is not really surprising: how could you say objectively that something (qualia) exists which cannot be grasped objectively?' },
    {type: ParagraphType.Paragraph, content: 'Many others oppose the concept, notably Dennett, but also [Churchland, Drescher, Lewis, Tye, Scruton—@<a href="https://en.wikipedia.org/wiki/Qualia">wiki</a>]. Famous scientists also support this view [Minsky]. Their arguments are not very convincing either (though not less convincing than proponents’), which is again not surprising: one does not objectively disprove the existence of something that, by nature, cannot be objectively grasped. ' },
    {type: ParagraphType.Paragraph, content: 'Mainly, views that oppose qualia propose that due to the nature of the concept, the question can only remain open, notably invoking [Nietzsche, Kant, Occam]. It seems that philosophers are not soon converging to a consensual definition and status concerning qualia. ' },
    {type: ParagraphType.Paragraph, content: 'This short article is intended to offer a bit of perspective to the problem. ' },
    
    {type: ParagraphType.Title, content: 'III. Personal views' },
    {type: ParagraphType.Paragraph, content: 'A few questions naturally arise when studying the question of consciousness: ' },
    {type: ParagraphType.Paragraph, content: 'Are people always present to themselves? What about habits? Consider for example a bus driver. After a few hundred times driving the same circuit every day, the driver will not even need to be bear attention to signs or to the road. The same goes when someone learns biking, and then when they are used to it, they need not put their consciousness to perform the act. They can let their mind wander, thinking things, not really needing to be present to the world. This suggests that experiences of the world, henceforth qualia, do not display constancy. ' },
    {type: ParagraphType.Paragraph, content: 'Is there really a problem considering a population from an external point of view—a third person view? From a materialist point of view, consciousness can be thought of as a central system, which gathers stimuli and generates appropriate responses, whether be it emotional or physical ones. Those responses are distinct from reflexes which bypass the central system, as preferential circuits were progressively carved into the less-conscious mind owing to repetition, forming that which is called “habits.” This central system of consciousness is undoubtedly important to learning and adapting to the environment—hence survival. Therefore, it might be a device that progressively emerged from an evolutionary perspective [<a href="https://en.wikipedia.org/wiki/On_the_Origin_of_Species">Darwin</a>]; there is a genetic component to consciousness. What remains then? Why should the change from an external perspective to a first-person view introduce anything more? (note: of course one should not be denying the existence of bliss or suffering, these also exist from an external perspective) ' },
    {type: ParagraphType.Paragraph, content: 'What about qualia in other animals? Is there always one quale per individual? Some argue that numbering individuals is not trivial [<a href="https://plato.stanford.edu/entries/identity-personal/">Olson 2015</a>]. What about machines, swarm animals, plants? Populations?' },
    {type: ParagraphType.Paragraph, content: 'From the questions raised in this section, the reader might guess that I advocate against the existence of qualia, that I think there is no “ghost in the shell,” but this is not the case. Experiencing the world and the fact of being there is so peculiar and seems so mysterious, that I can only think that there is something lacking in a vision without qualia. Simply, the emergence of something as ungraspable as a quale must be due to precise dispositions in thought. ' },
    {type: ParagraphType.Paragraph, content: 'Let’s consider you are in a room filled with philosophers. I am not a philosopher, so I am waiting outside. When I observe the room from the outside, I can see a set of individuals, each bearing their own consciousness, acting, thinking and talking according to their dispositions and experiences. No real need for qualia. Now what do you see? The same, essentially, a group of philosophers with their ideas and identities, but there seems to be something more. You can see the world around you, you can hear the voices, feel the air, look into their eyes, and feel completely immersed in your environment. And it is only when you realize this, that you find yourself convinced with your own existence (as a quale). ' },
    {type: ParagraphType.Paragraph, content: 'This might be the most important point: qualia cannot be an ever-present subset of consciousness. Rather, quale can be thought of as the phenomenon that appears only when a thinker thinks about the fact that he or she is thinking. When a feeler feels that he feels. Remember, in the beginning we are only being present to the world. Realizing this fact is a consequence, and the problem of qualia is asked only as a consequence of consciousness inquiring about everything, including itself. This doesn’t amount to saying that “if there is no one to ask the question of qualia, then there is no mystery,” but, rather, that a deceptive feeling of mystery may arise when one thinks about themselves, where there is indeed no mystery but the only accessible, fundamental truth of the individual: I am alive. ' },
    {type: ParagraphType.Paragraph, content: 'It is only when we let our minds wander that they eventually come back to themselves. Only then can we ask the question “why am I me and no other?”: quale can be a source of wonder as well as existential angst. For the best, we may as well focus on the wonder of wandering machines [<a href="https://www.goodreads.com/book/show/322340.La_Domestication_De_L_tre">Sloterdijk 2000</a>] and ignore angst which is only its own cause and which can only fuel itself further. ' },
    {type: ParagraphType.Paragraph, content: 'Finally, I would argue that the proposed conception of qualia as a self-phenomenon emerging from the thought of thought, or rather the feeling of feeling, agrees with the properties described by [<a href="https://www.goodreads.com/book/show/7961401-quining-qualia">Dennett 1988</a>]: they are intrinsic, private, apprehensible in consciousness, and arguably ineffable. In this context, I essentially believe this question is a pathological corollary of thought and feeling: how many of our kinsfolk, who are neither curious nor interested in philosophy, have ever felt the urge of answering the question of qualia or existential angst? Maybe not that many (which remains to be studied).' },
    {type: ParagraphType.Paragraph, content: '[<a href="https://en.wikipedia.org/wiki/G%C3%B6del%27s_incompleteness_theorems">Godel</a>] gives an interesting argument, based on the liar’s paradox, about how self-referring propositions are pathological and may lead to aporias in arithmetic systems. This may lead to believe that thought for thought only brings more strangeness into the world, whereas we only long for simplicity and closure. ' },
    
    {type: ParagraphType.Title, content: 'IV. Digressions' },
    {type: ParagraphType.Paragraph, content: 'Building up from the concept of qualia as a phenomenon arising from self-awareness, it is tempting to draw an analogy to a larger problem. Let’s get back to the example of the room filled with philosophers. ' },
    {type: ParagraphType.Paragraph, content: 'I proposed that an external observer would have no need to consider qualia. But this observer is part of a larger system. As such, it can be subject to the phenomenon of qualia itself. So talking about the universe at large always depends on some point of view which is part of said universe, be it the point of view of a community, or a subset of the universe. ' },
    {type: ParagraphType.Paragraph, content: ' “Conscious” life, notably with the emergence of a philosophical community, is, to some extent, a way for the universe to enquire about itself. Metaphysics is a protrusion of the quale of philosophy. ' },
    {type: ParagraphType.Quotation, content:
        'We have no need of other worlds. We need mirrors. ',
        origin: 'Stanisław Lem',
        source: 'Solaris'
    },

    {type: ParagraphType.Paragraph, content: 'Reading [Dennett], I found it delightful to think that “Quining” in “Quining Qualia” could have meant that there be a parallel between programming quines and qualia. ' },
    {type: ParagraphType.Paragraph, content: 'There are some aspects that were not mentioned in this article, but that would deserve a further elaboration, among which cultural aspects (do you think you would convince yourself you have a consciousness because other people keep talking about it?), or the relationship between the multiplicity of qualia and time. ' },

    {type: ParagraphType.Paragraph, content: 'Quick update following this awesome take by <a href="https://www.youtube.com/watch?v=h6fcK_fRYaI"><i>In a Nutshell</i></a> on the multiplicity of qualia, which illustrates a story by <a href="https://www.goodreads.com/author/show/6540057.Andy_Weir">Andy Weir</a>. We could elaborate a discussion from the aforementioned issue: why am I <i>me</i> and no other? Which we said was not a real issue, but let us reformulate it in terms of qualia: if I am a quale, it is reasonable to think every other person on the globe—even some animals for what we know—also is a quale, albeit a different one. So what distinguishes <i>me</i> from <i>them</i>? What does being a different one mean? '}, 
    {type: ParagraphType.Paragraph, content: 'This is a very interesting question, which admits different valid answers depending on the person who answers, and even no answer if it is asked objectively to the universe or to the abyss that stares back at you. Andy Weir and the creators of <i>In a Nutshell</i> formulate the possibility that, based on reincarnation, there really is only one quale in the universe, and everyone’s life, at one point in this <i>meta-chronology</i> of reincarnation, is incarnated by it. This point of view is very interesting. Though the argument of the existence of a specifically-ordered chronology can be challenged, it makes no doubt that as long as you, the reader, have a unique experience of the world around you, then so does everyone else on Earth. And nothing makes your experience of the world more valuable than another’s. Evil comes from the failure of some to understand that. '}, 
    {type: ParagraphType.Paragraph, content: 'The existence of you, and others, makes no doubt. A little more doubtfully, I would also argue for the existence of the present moment, whatever hidden mechanisms make it pulse and flow the way it does. But even if this holds true, and as a consequence you do not actually go back and forth in time to incarnate, the mere presence of others should be enough for you to acknowledge not being alone to feel... '}, 
  ]
}; 
return a2;      
}}

// - Are qualia only related to perception and conception? Or is this something deeper? 
// From the definition, I would argue that qualia have nothing to do with a difference in perception or conception, 
// which are simply different mental representations or constructions, varying according to the individual. 
// [Feynman] illustrates this by considering people mentally counting up to one minute: some would imagine 
// a voice dictating the numbers; others would visualize cards being .
