import {ParagraphType} from '../article';
export class A1 { static get() {
const a1 = 
{ title: 'Science and knowledge',
  date: '2019/08/23',
  author: 'm. s', 
  body: [
    {type: ParagraphType.Title, content: 'Foreword' },
    {type: ParagraphType.Paragraph, content: 'Please be so kind as to let me go on with my streak of rambling philosophical articles with presumptuous titles. Well, the main reason I wrote this one was to give my opinion about science even though no one asked for it, so here it is.' },
    {type: ParagraphType.Paragraph, content: 'As usual, I do not have any interest in promoting any ideology and I do not own an official degree in philosophy. I do not think anyone will read this so there is no option for feedback. ' },
    
    
    {type: ParagraphType.Title, content: 'I. Science to scientists' },
    {type: ParagraphType.Paragraph, content: 'The question behind the definition of science is neither a problem of terminology nor an end in itself. It reflects a deeper concern: how do we - how should we - properly inquire about the world and enhance our understanding of things? What should be the central characteristic, the rule of thumb, to any attempt to fathoming the universe? ' },
    {type: ParagraphType.Paragraph, content: 'There is no unique right answer as there is no unique right method prevailing in all domains of science. Nonetheless, [<a href="http://www.theses.fr/2016PA040002">Barrau</a>] identified some tendencies: ' },
    {type: ParagraphType.Paragraph, content: 'A first perspective is that sciences mostly rely on mathematics [Plato and geometers, Galileo and the language of nature, Einstein and geometry]. One can argue that not all sciences make use of mathematics, notably sub-domains of biology and social sciences. Moreover, tools offered by mathematics are contextual, they keep evolving together with the needs of scientific domains that use them. ' },
    {type: ParagraphType.Paragraph, content: 'A second perspective would be that sciences are able to produce accurate predictions. This is indeed an important criterion for building confidence in scientific models and theories [Thales with an eclipse, Einstein with gravitational waves, <a href="https://en.wikipedia.org/wiki/Higgs_mechanism">ABEGHHK\'tH</a> with the Higgs boson], and sometimes leads to discontinue certain researches. However, the ability to predict something is not linked to a profound understanding of the mechanisms at play in a system [<a href="https://arxiv.org/pdf/1101.0891">G. Shmueli</a>, <a href="https://www.goodreads.com/book/show/16122061-pr-dire-n-est-pas-expliquer">R. Thom</a>]. The ability to predict actually generates "knowledge" in a weaker version than justified true belief [<a href="https://www.goodreads.com/book/show/26804279-is-justified-true-belief-knowledge">Gettier</a>], where the notion of "true" can be checked by evaluating the prediction, and the notion of "justified" has been reduced to that evaluation.' },
    {type: ParagraphType.Paragraph, content: 'A third perspective would be to consider science as a method based on experiments. By letting the world decide what is possible or not, science becomes subordinate to the truth that the experiments bear out. In this perspective, the status of mathematics as a science can be debated. Whether mathematics are considered as a language subject to cultural bias, or as something dependent on the local physical laws, or as a process whose progressive elaboration depended on its ability to accommodate to observations and applications, or as something completely universal (which can be debated), or as mere thought experiments, the real relationship between mathematics and experiment remains unclear. More importantly, what about the aftermath of experiments? Their outcomes is just raw data, which is then subject to interpretation. ' },
    {type: ParagraphType.Paragraph, content: 'A fourth perspective would subject sciences to the dominion of logic and rationality. But in the realm of logic, a conception of science as that which advances knowledge in the form of justified true belief is probably not enough [Gettier]. In its modern aspect, formal logic is but a formalism, a cultural construction; and rationality is the ultimate aspiration of every school of thought before (even after) they are proved wrong. ' },
    {type: ParagraphType.Paragraph, content: '[Barrau]\'s original take on the problem of defining science is tempting though not restrictive enough for my taste: the scientific tale is a tension between creative freedom (the scientist is seen as a creator of models searching for truth and beauty [Atiyah]) and the facts enforced by reality. Facts and observations constrain the creative power of scientists, but as he argues, theories are under-determined by facts (well, he is a cosmologist), though only to some extent (he is careful enough not to go further down that road). With a respectable attempt to keep the possibilities of science open and inclusive, [Barrau] still wields a conception of science a posteriori, without really going into the core of what it is that makes it fascinating and worth to contribute to. ' },
    
    {type: ParagraphType.Title, content: 'II. Science to the telescope operator' },
    {type: ParagraphType.Paragraph, content: 'I think all these definitions lack something personal, some relationship between science and individuals. Why is it that people do science? I cannot speak for many, but I will give my own reason nonetheless: genuine curiosity. Curiosity without a second thought, curiosity that comes right after wonder or horror. You will try your hardest not to be fooled when you are genuinely curious about finding out something, consequently minimizing cultural, social and economical influences over your discoveries and interpretations. ' },
    {type: ParagraphType.Paragraph, content: 'An immediate enemy is the thirsty curiosity, which emerges from the desire to keep on observing or discovering wonderful things in nature, just for the sake of seeing wonderful things; this curiosity is better suited for arts. Another potential enemy is the destructive curiosity, which damages the object of study in order to collect truths about it; discussions on this subject are complex and related to epistemology, moral philosophy, biology, medical sciences. ' },
    {type: ParagraphType.Paragraph, content: 'When possible, I would promote the curiosity of a telescope operator in the seventeenth century. ' },
    
    {type: ParagraphType.Title, content: 'III. Modernity' },
    {type: ParagraphType.Paragraph, content: 'The history of knowledge underwent a (more or less) recent crisis of foundations, which impacted mathematics with the advent of axioms and formal systems; high energy physics and the search for unified laws; cosmology and the quest for an initial singularity; phylogenetics and the inquiry about the origin of life and species; along with many more domains. The history of science and epistemology is long and complex, but there seems to be an obvious trend. A ideal quest for unity? A tendency to deism, to cut the real with [<a href="https://en.wikipedia.org/wiki/Occam%27s_razor">Occam\'s razor</a>] until there is only one singularity left? ' },
    {type: ParagraphType.Paragraph, content: 'This ideal quest disagrees with the branching nature of sub-domains of knowledge, which grow exponentially as many nuances are introduced over the course of new discoveries, when studying phenomena at least. An argument in favor of this quest for unity comes from [<a href="https://en.wikipedia.org/wiki/Chaos_theory">Chaos theory</a>]: from <a href="https://en.wikipedia.org/wiki/Logistic_map">simple</a> rules, complex systems can emerge. The study of consequences is therefore an ever-branching science filled with nuances and peculiar observations. ' },
    {type: ParagraphType.Paragraph, content: 'However, chaos only proves that a system with simple rules can generate complex worlds; none can be said about the actual world. Besides, what are simple rules to begin with? Rules that can be concisely encoded with respect to a particular formalism or language? This concept seems arbitrary, though I have no doubt it could be thoroughly formalized to yield something somewhat disappointing and all-encompassing, or only encompassing algebra. The point is that there is no "trivial" rule, i.e. no rule that can be encoded with only one bit. Or if there was, knowing it would not add to our knowledge. It would do nothing.' },
    {type: ParagraphType.Paragraph, content: 'Therefore, if there were actual rules for the universe that would be written with some sort of indelible ink into the very fabric of existence, these could be arbitrary complex rules with respect to human intellect. Furthermore, these rules should contain themselves. <small><a href="https://en.wikipedia.org/wiki/G%C3%B6del%27s_incompleteness_theorems">Right?</a></small> ' },
    
    {type: ParagraphType.Title, content: 'IV. Fragments and unasked questions' },
    {type: ParagraphType.Paragraph, content: 'Rules from the world are inferred. They have changed throughout the history of science and "knowledge". But as the answers keep on changing, the quest for the most fundamental remains. Yet what is the most fundamental? Matter, energy? Time, space? Information? Some structure or unwinding process? Our direct experience of the world? From the point of view of an individual, the latter seems reasonable [Descartes\' <a href="https://en.wikipedia.org/wiki/Meditations_on_First_Philosophy">cogito</a>, Sartre\'s <a href="https://en.wikipedia.org/wiki/Existentialism_Is_a_Humanism">existence</a>, Schopenhauer\'s <a href="https://en.wikipedia.org/wiki/The_World_as_Will_and_Representation">representation</a>]. From the point of view of a community of knowledge, such as the scientific community, it would be more of a consensus, a ground of non-controversy built a posteriori, gathered from the many fragments of individual scientists\' opinions. From the point of view of the world itself, does this mean anything?' },
    {type: ParagraphType.Paragraph, content: 'Why even search for the most fundamental anyway? My personal take is that fundamental philosophical inquiries about the world, though fascinating they are, are in fact not "fundamental", in the sense that it would suppose foundations which are cultural in nature. Every building needs foundations to stand up; but not everything is a building. A building is a part of the world, which does not encompass the whole world.' },
    {type: ParagraphType.Paragraph, content: 'Far-reaching metaphysical questions are either ill-defined ("why is there a universe rather than nothing?", which assumes there is ground to answer the question, therefore assumes there is something prior to the existence of the universe, which is a contradiction), or really far from our daily concerns ("is the universe discrete?", which could be endlessly discussed and still remain interesting).' },
    {type: ParagraphType.Paragraph, content: 'On a positive note, I believe that pointing out the contradictions and social or cultural assumptions behind ill-defined metaphysical questions ("is there an afterlife?", "what was there before the beginning?") should be easy. In the worst case, those questions could be rephrased and the underlying genuine philosophical problems could be presented for what they are, in a considerably less frightening perspective. Then we would be left wondering about the actual marvels of being there, surrounded by incredible diversity, curious eyes gazing at the farthest stars in the night sky.' },
    {type: ParagraphType.Paragraph, content: 'Remember that in the beginning, there was no language and no questions, probably just the fact of being present to the world, together with all the other earth-dwellers. ' },
  ]
}; 
return a1;      
}}
