import {ParagraphType} from '../article.js';
export class A1 { static get() {
const a1 = 
{ title: 'What does it take to do science?',
  date: '2019/08/23',
  author: 'M. S', 
  thumb: 'assets/img/craft/science.jpg',
  body: [ 
    {type: ParagraphType.Title, content: 'I. Science to scientists and poets' },
    {type: ParagraphType.Paragraph, content: 'The question behind the definition of science is neither a problem of terminology nor an end in itself. It reflects a deeper concern: how do we—how should we—properly inquire about the world and enhance our understanding of things? What should be the central characteristic, the rule of thumb, to any attempt to fathoming the ways of the universe? ' },
    {type: ParagraphType.Paragraph, content: 'There is no unique right answer as there is no unique right method prevailing in all domains of science. Nonetheless, [<a href="http://www.theses.fr/2016PA040002">Barrau</a>] identified some tendencies: ' },
    {type: ParagraphType.Paragraph, content: 'A first perspective is that sciences mostly rely on mathematics [Plato and geometers, Galileo and the “language of nature,” Einstein and geometry]. One can argue that not all sciences make use of mathematics, notably sub-domains of biology and social sciences. Moreover, tools offered by mathematics are contextual, they keep evolving together with the needs of scientific domains that use them. ' },
    {type: ParagraphType.Paragraph, content: 'A second perspective would be that sciences are able to produce accurate predictions. This is indeed an important criterion for building confidence in scientific models and theories [Thales with an eclipse, Einstein with gravitational waves, <a href="https://en.wikipedia.org/wiki/Higgs_mechanism">ABEGHHK’tH</a> with the Higgs boson], and sometimes this leads to discontinue certain researches. However, the ability to predict something is not linked to a profound understanding of the mechanisms at play in a system [<a href="https://arxiv.org/pdf/1101.0891">G. Shmueli</a>, <a href="https://www.goodreads.com/book/show/16122061-pr-dire-n-est-pas-expliquer">R. Thom</a>]. The ability to predict actually generates “knowledge” in a weaker version than justified true belief [<a href="https://www.goodreads.com/book/show/26804279-is-justified-true-belief-knowledge">Gettier</a>], where the notion of “true” can be checked by evaluating the prediction, and the notion of “justified” has been reduced to that evaluation.' },
    {type: ParagraphType.Paragraph, content: 'A third perspective would be to consider science as a method based on experiments. By letting the world decide what is possible or not, science becomes subordinate to the truth that the experiments bear out. In this perspective, the status of mathematics as a science can be debated. Whether mathematics are considered as a language subject to cultural bias, or as something dependent on the local physical laws, or as a process whose progressive elaboration depended on its ability to accommodate to observations and applications, or as something completely universal (which can be debated), or as mere thought experiments, the real relationship between mathematics and experiment remains unclear. More importantly, what about the aftermath of experiments? Their outcome is just raw data, which is then subject to interpretation. ' },
    {type: ParagraphType.Paragraph, content: 'A fourth perspective would subject sciences to the dominion of logic and rationality. But in the realm of logic, a conception of science as that which advances knowledge in the form of justified true belief is probably not enough [<a href="https://www.goodreads.com/book/show/26804279-is-justified-true-belief-knowledge">Gettier</a>]. In its modern aspect, formal logic is but a formalism, a cultural construction; and rationality is the ultimate aspiration of every school of thought before—and even after—they are proved wrong. ' },
    {type: ParagraphType.Paragraph, content: 'Barrau’s original take on the problem of defining science is tempting though not restrictive enough for my taste: to him, the scientific tale is a tension between creative freedom (the scientist is a creator of models searching for “truth and beauty” [Atiyah]) and the facts enforced by reality. Facts and observations constrain the creative power of scientists, but as he argues, theories are under-determined by facts (well, he is a cosmologist). With a respectable attempt to keep the possibilities of science open and inclusive, Barrau still wields a conception of science a posteriori, without really going into the core of what it is that makes it fascinating and worth to contribute to. ' },
    
    {type: ParagraphType.Title, content: 'II. Science to the layman made scientist' },
    {type: ParagraphType.Paragraph, content: 'All these definitions, though equally insightful and interesting, lack something personal; some relationship between science and individuals. Why is it that people do science in the first place? A child’s answer could be the right answer: curiosity! Curiosity without a second thought, curiosity that comes right after wonder or horror. You will try your hardest not to be fooled when you are genuinely curious about finding out something, consequently minimizing cultural, social and economical influences over your discoveries and interpretations. ' },
    {type: ParagraphType.Paragraph, content: 'An immediate enemy is the thirsty curiosity, which emerges from the desire to keep on observing or discovering wonderful things in nature, just for the sake of seeing wonderful things; seeking beauty is associated with avoiding ugliness, even if it is a part of nature. This curiosity is better suited for the arts. Another potential enemy is the destructive curiosity, which damages the object of study in order to collect truths about it; discussions on this subject are complex and related to epistemology, moral philosophy, biology, medical sciences. ' },
    
    {type: ParagraphType.Title, content: 'III. Loophole in fundamental science' },
    {type: ParagraphType.Paragraph, content: 'The history of knowledge underwent a (more or less) recent crisis of foundations, which impacted mathematics with the advent of axioms and formal systems; high energy physics and the search for unified laws; cosmology and the quest for an initial singularity; phylogenetics and the inquiry about the origin of life and species; along with many more domains. The history of science and epistemology is long and complex, but there seems to be an obvious trend. An ideal quest for unity? A tendency to deism, to shave reality with [<a href="https://en.wikipedia.org/wiki/Occam%27s_razor">Occam’s razor</a>] until there is only one singularity left? ' },
    {type: ParagraphType.Paragraph, content: 'Only in appearance does this ideal quest disagree with the branching nature of sub-domains of knowledge, which grow exponentially as many nuances are introduced over the course of new discoveries, at least when studying phenomena. An argument in favor of the existence of “unique,” simple rules to the universe actually comes from [<a href="https://www.goodreads.com/book/show/64582.Chaos">Chaos theory</a>]: from <a href="https://en.wikipedia.org/wiki/Logistic_map">simple</a> rules, complex systems can emerge. The study of consequences is therefore an ever-branching science filled with nuances and peculiar observations. ' },
    {type: ParagraphType.Paragraph, content: 'However, chaos says nothing about the actual world. If there were actual rules for the universe that would be written with some sort of indelible ink into the very fabric of existence, these could be arbitrary complex rules with respect to the human intellect. <small>Furthermore, these rules should contain themselves, <a href="https://en.wikipedia.org/wiki/G%C3%B6del%27s_incompleteness_theorems">right?</a></small> Besides, what are simple rules to begin with? Rules that can be concisely encoded with respect to a particular formalism or language? This seems arbitrary and somewhat circular. What can be said, for sure, is that there is no interest in a “singular” rule, i.e. a rule that can be encoded with only one bit, for (1) the universe contains information, and (2) if there was such a singular rule, knowing it would not add to knowledge; it would do nothing. Likely, the effort to seek a ultimate model for the universe is fated to disappoint. ' },

    {type: ParagraphType.Title, content: 'IV. Unasked questions' },
    {type: ParagraphType.Paragraph, content: 'Scientific laws are inferred. They have changed throughout the history of science and “knowledge.” Yet as the answers keep on changing, the quest for the most fundamental remains. However, fundamental inquiries about the world, though fascinating they are, can never be “fundamental,” in the sense that they would suppose foundations, which are a cultural construct. Every building needs foundations to stand up; but not everything is a building. A building is a part of the world, which does not encompass the whole world. ' },
        {type: ParagraphType.Paragraph, content: 'Some philosophers argue that from the point of view of an individual, the most fundamental is our direct experience of the world [Descartes’ <a href="https://en.wikipedia.org/wiki/Meditations_on_First_Philosophy">cogito</a>, Sartre’s <a href="https://en.wikipedia.org/wiki/Existentialism_Is_a_Humanism">existence</a>, Schopenhauer’s <a href="https://en.wikipedia.org/wiki/The_World_as_Will_and_Representation">representation</a>]; and the world itself along with its mysterious ways is the farthest away from these foundations of being. From the point of view of a community of knowledge, such as the scientific community, the foundation would be more of a consensus, a ground of non-controversy built a posteriori, gathered from the many fragments of individual scientists’ opinions. Existential questions about the foundation of <a href="https://www.goodreads.com/book/show/8694.Life_the_Universe_and_Everything">Life, the Universe and Everything</a> would then require to have access to the point of view of the world itself. ' },
        {type: ParagraphType.Paragraph, content: 'From simple observation and reflection, seemingly far-reaching metaphysical questions can then be shown to be either ill-defined (“why is there a universe rather than nothing?” which assumes there is ground to answer the question, therefore assumes there is something prior to the existence of the universe, which is a contradiction), or really far from daily concerns (“is the universe discrete?”, which could be endlessly discussed and still remain interesting). On a positive note, pointing out the contradictions and social or cultural assumptions behind ill-defined metaphysical questions (“is there an afterlife?”; “what was there before the beginning?”) should be easy. In the worst case of existential angst, those questions could be rephrased and the underlying genuine philosophical problems could be presented for what they are, in a considerably less frightening perspective. Then we would be left wondering about the actual marvels of being there, surrounded by incredible diversity, curious eyes gazing at the farthest stars in the night sky.' },
    {type: ParagraphType.Paragraph, content: 'Remember that in the beginning, there was no language and no questions, probably just the fact of being present to the world, together with all the other earth-dwellers. ' },

  ]
}; 
return a1;      
}}
