import {ParagraphType} from '../article';
export class A3 { static get() {
const a3 = 
{ title: 'Purpose',
  date: '2019/08/20',
  author: 'm. s',
  body: [
    {type: ParagraphType.Title, content: 'Foreword and conflict of interest' },
    {type: ParagraphType.Paragraph, content: 'Here is a short, colloquial first article with the boldest of titles, hopefully nothing goes wrong. In the following, I present my personal view concerning the meaning of life - this sounds really arrogant, but everyone has thought about it at one point, so please let me proceed. ' },
    {type: ParagraphType.Paragraph, content: 'I do not have any interest in promoting any ideology and I do not own an official degree in philosophy (which may be inferred from the text).' },
    
    
    {type: ParagraphType.Title, content: 'I. Meaning of meaning' },
    {type: ParagraphType.Paragraph, content: 'Because it is always nice to dig right into the dark side of thought, namely meta-thinking, I would like to point out that the concept of "meaning" (as well as the concept of "concept") is a meta-concept in essence. As is the concept of "essence", I gather. Which makes it quite difficult to talk seriously about that matter, really. ' },
    {type: ParagraphType.Paragraph, content: 'Therefore, I will assume for the remainder of this short article that the reader is familiar with what "meaning" means, or at least that the reader understands "meaning" approximately the same way I do, though now I am not really sure what it means anymore.' },
    
    {type: ParagraphType.Title, content: 'II. Meaning of you' },
    {type: ParagraphType.Paragraph, content: 'A first aspect of the question of the meaning of an individual\'s life is the (cultural) question of destiny. Is there a predefined meaning of life?' },
    // - argument: destiny is unimportant
    {type: ParagraphType.Paragraph, content: 'I will not argue over the existence, or lack thereof, of destiny in the real world. Rather, I will try to argue that whether destiny is real or not is irrelevant to us. As we are not considering the world itself as the object of our study, let us assume that it is subject to Newtonian, linear time. In this context, the world is either deterministic (the future depends at most on the past and present), or non-deterministic (all other cases). One could be tempted to argue that the future is a mental picture which does not actually exist, that there is only the present, or that the present has a duration [W. Heisenberg], or that time is mass [R. Penrose]. This is not really relevant here, for we are just talking about the history and the future of individual human beings. ' },
    {type: ParagraphType.Paragraph, content: 'In a non-deterministic world, the idea of destiny would suppose that no matter past and present causes, a certain future is already there. This calls for determinism, or resilience to non-determinism, at least on a local level. As chaotic systems have a tendency to spread and yield intractable effects, I think that the idea of local resilience in a non-deterministic world is quite far-fetched. I would be tempted to discard the idea of destiny in this case.' },
    {type: ParagraphType.Paragraph, content: 'In a completely deterministic world, there is only one possible future. This is exactly what the idea of destiny states. However, because of chaotic systems [H. Poincaré], the one possible future cannot exactly be predicted. It can be approximated, requiring huge computational power, to the extent that performing a prediction with a supercomputer may have economical consequences (Tianhe 1-A = 4.04 MW), thus in our case consequences on the system being studied. Therefore, exact and certain knowledge of the future is inaccessible to us humans, even in a deterministic world. Yet, knowledge can only be valuable when it is accessible. Take for instance [normal numbers]. They contain every possible book in their decimals, so why bother writing? Because books in decimals are inaccessible knowledge. They are too many, they exist along with versions of them with typos and grammar mistakes.' },
    {type: ParagraphType.Paragraph, content: 'Now that does not discard the possibility of the future being accessible to some cosmic entity (note: it proves quite difficult to talk about this matter without being culturally biased). But is a cosmic entity going to land on earth and start to do things because it has the knowledge of one individual\'s destiny? This, again, seems far-fetched to me. And what about happy coincidences? One can argue there are also unhappy coincidences. My point here is that there is no observable difference between a certain event which was triggered by a whirling of complex events, or by a single (cosmic) entity, as such events are neither predictable nor reproducible [K. Popper]. If some cosmic entity was to watch over me and give my life meaning, I would be dubious about why such a cosmic entity would care about little details in my life and not care about the suffering and death of people in countries devastated by famine and war. Or maybe would the cosmos care about little details in their life as well? As the shape of the clouds they see when they are starving? I think not.' },
    {type: ParagraphType.Paragraph, content: 'Therefore I would argue against the concept of a predefined, a priori meaning of life.' },
    {type: ParagraphType.Paragraph, content: 'I would rather argue to defend my own personal view on the meaning of one\'s life, which is that it is something that is built over time as the result of one\'s inner motivations and interactions with the exterior and other people. This is similar to the concept of [tabula rasa] in the domain of knowledge.' },
    // - argument: others\' lives
    {type: ParagraphType.Paragraph, content: 'The only real argument I can give to support my view is that when you consider the past lives of human beings, many were devoid of a grand, mysterious meaning. Few people have lived who could say their meaning was different than founding a family, helping others, finding happiness or achievement in work and art. Those were certainly hard-fought meanings. Then why should mine be different? Looking at those who lived, I know what to expect and what not to expect.' },
    {type: ParagraphType.Paragraph, content: 'The nice thing about this vision is that you get your say in what your life should be, but at the same time the (local) universe gets to influence your path, whether changing its course or making it easier or harder to walk. This is neither out of proportion nor humility.' },
    
    {type: ParagraphType.Title, content: 'III. Meaning of the world' },
    {type: ParagraphType.Paragraph, content: 'Another interesting question arises when considering the multiplicity of individual purposes on planet Earth. Is there some sort of "special meaning", directed towards us, for the world to exist? To [Feynman], that would be indeed "out of proportion", with respect to what exists in the universe at large.' },
    {type: ParagraphType.Paragraph, content: 'If there is no such pre-established meaning, is it desirable to build one? How can we build it? The question is quite complex, and raises the problems of society, economy, politics, anthropology and ecology (as the branch of biology that studies relationships between living beings and their environment). ' },
  ]
};
return a3; 
}}
