import {ParagraphType} from './article';

export class Technical {

  static getArticles() {
    const articles = [
      // {
      //   title: 'Useful links',
      //   author: 'm.s',
      //   date: '2017/01/10',
      //   body: [
      //     {type: ParagraphType.ListItemFR, content: 'Références'},
      //     {type: ParagraphType.Link, content: 'http://google.com', heading: 'Google'}
      //   ],
      //   validated: true
      // },
      {
        // id: -2,
        title: 'CPU-based 2D particle tracing',
        author: 'm.s',
        type: 'welcome',
        date: '2019/02/05',
        body: [
          {type: ParagraphType.Image, content: 'assets/img/2.png'},
          {type: ParagraphType.Title, content: 'Introduction'},
          {type: ParagraphType.Paragraph, content:
              'This short article presents a method for rendering particles on the CPU, ' +
              'which is easy to implement but not quite adapted for real-time graphics, ' +
              'as the CPU may be put to more profitable use. '
          },
          {type: ParagraphType.Title, content: 'I. Particle-based visualization and unsteady vector fields'},
          {type: ParagraphType.Paragraph, content:
              'The visual shown above was obtained with a basic technique called particle advection. ' +
              'It has been used for wind visualization in the browser for quite some time, ' +
              'see the <a href="https://github.com/cambecc/earth">earth project started in 2013</a>, ' +
              'which takes inspiration from <a href="http://hint.fm/wind/">hint.fm</a> and ' +
              'has inspired <a href="https://github.com/Esri/wind-js">windy.js</a>. '
          },
          {type: ParagraphType.Paragraph, content:
              'A vector field defined on a geometrical domain ' +
              'associates every position in the domain with a distinct vector. ' +
              'Continuous vector fields can be used to represent flow. ' +
              'For instance, when looking at the earth from a very high altitude, wind can be seen ' +
              'as a 2D vector field defined on the Earth\'s 2D surface, ' +
              'considering the atmosphere\'s height is negligible. ' +
              'If the vector field stays the same throughout time, it is called steady. ' +
              'If not, it is called unsteady. '
          },
          {type: ParagraphType.Paragraph, content:
              'There are different ways to get visual insights about vector fields: ' +
              'drawing tiny glyphs, like arrows locally pointing in the direction of ' +
              'the flow; ' +
              'texture advection techniques such as the ' +
              '<a href="https://en.wikipedia.org/wiki/Line_integral_convolution">' +
              'LIC</a> which "combines" random noise with the vector field; ' +
              'extraction of integral curves such as ' +
              '<a href="https://en.wikipedia.org/wiki/Streamlines,_streaklines,_and_pathlines">' +
              'streamlines, pathlines, timelines, streaklines</a>; ' +
              'extraction of characteristic scalar fields such as the ' +
              '<a href="https://en.wikipedia.org/wiki/Divergence">divergence field</a> ' +
              'that can easily be visualized with a heatmap; ' +
              'or particle advection which simply consists in launching many virtual particles ' +
              'that locally follow the flow. ' +
              'The latter is akin to progressively tracing randomly seeded pathlines. '
          },
          {type: ParagraphType.Paragraph, content:
              'Computing the field\'s topology may provide further insight. ' +
              'Broadly speaking, it allows to track singularities in the flow, ' +
              'or to identify geometric zones where the flow\'s behaviour is homogeneous. ' +
              'The most important singularities are often called <i>critical points</i>. ' +
              'These may correspond, for instance, to the center of vortices. '
          },

          {type: ParagraphType.Title, content: 'II. Making up a vector field'},
          {type: ParagraphType.Paragraph, content:
              'When someone wants to draw a cute visual just for the sake of ' +
              'it, they do not really care whether the underlying dynamics ' +
              'are physically realistic or not. ' +
              'Rather, staring at those wind maps for a while must have one realize ' +
              'that what\'s captivating about them ' +
              'dwells in their peaceful rotation and lack of symmetry. '
          },
          {type: ParagraphType.Paragraph, content:
              'So let\'s set up a vector field on a small rectangular geometric domain. ' +
              'The field would be generated by a fixed number of vortices. ' +
              'Every vortex that shall be thrown into the domain should have ' +
              'two properties: a range ' +
              'defining the span of its influence zone, and an intensity ' +
              'defining how strong the vector field would be near it. ' +
              'The sign of the intensity term would determine whether ' +
              'the field would spin clockwise or counter-clockwise.'
          },
          {type: ParagraphType.Equation, content:
              '\\mathbf{v} = \\mathbf{p} \\times (\\mathbf{z} \\cdot \\text{intensity} ' +
              '\\cdot e^{- \\frac{1}{\\text{range}} \\cdot \\lVert \\mathbf{p} \\rVert }) '
          },
          {type: ParagraphType.Paragraph, content:
              'For one single vortex, this formula gives v, a three-dimensional (!) vector, ' +
              'for any position p, when the origin is taken ' +
              'at the only vortex. The vector z denotes the unit vector orthogonal ' +
              'to the domain; the multiplicative symbol denotes the cross product. ' +
              'Take the first two coordinates of v to get the desired ' +
              'two-dimensional vector. ' +
              'Now the only remaining task is to add the contribution of multiple vortices. '
          },
          {type: ParagraphType.Equation, content:
              '\\mathbf{V} = \\sum_{\\text{vortices}} \\mathbf{v}'
          },
          {type: ParagraphType.Paragraph, content:
              'V is the resulting vector field. ' +
              'This is just a simple sum of the contributions of all vortices. ' +
              'Bear in mind that p is distinct for every vortex. ' +
              'When computing this sum in practice, ' +
              'the intensity decay due to the exponential factor ' +
              'makes it possible to use lookup structures to not ' +
              'test against every vortex in the domain. ' +
              ''
          },

          {type: ParagraphType.Title, content: 'III. Particles everywhere'},
          {type: ParagraphType.Paragraph, content:
              'This is the easiest part. ' +
              'No need to care about anything in particular here, ' +
              'just crazily add thousands of particles, ' +
              'and make them follow the flow. ' +
              'The position x of a particle at a given frame ' +
              'should be updated the next frame so that ' +
              'its new position equals the old position plus ' +
              'the value of the vector field at its old position. '
          },
          {type: ParagraphType.Equation, content:
              '\\mathbf{x}(t+1) = \\mathbf{x}(t) + \\mathbf{V}(\\mathbf{x}(t))'
          },

          {type: ParagraphType.Title, content: 'IV. Unsteady fields'},
          {type: ParagraphType.Paragraph, content:
              'Never in practice is wind velocity a simple, smooth, ' +
              'analytical vector field. Usually, it has to be either ' +
              'simulated with complex models or measured ' +
              'with technical instruments at a discrete number of locations. ' +
              'Some of the javascript applications that were introduced earlier ' +
              'query meteorological servers to get precomputed wind ' +
              'velocity fields. Then the actual value of the field at a given ' +
              'point is interpolated between known neighbour values. ' +
              'This works well for steady fields.'
          },
          {type: ParagraphType.Paragraph, content:
              'However, initially building the field and ' +
              'computing interpolations are expensive. ' +
              'Good news! There\'s no need to do any of that ' +
              'with the kind of vector field described in section II. ' +
              'This makes it actually possible to render <i>unsteady</i> ' +
              'vector fields, taking some precautions though. ' +
              'A simple adjustment can be made to the model, so that ' +
              'for instance vortices can move through the domain. ' +
              'This would not change anything concerning the ' +
              'computation of particles. '
          },
          {type: ParagraphType.Paragraph, content:
              'The drawback is that vortices must move consequently ' +
              'slower than particles, so that particles actually capture ' +
              'the state of the vector field at a given time. ' +
              'An attractive force between punctual particles is out of ' +
              'the question because there would be occasional ' +
              'outbursts in vortex velocities due to couples of vortices ' +
              'passing near one another. ' +
              'Repulsive forces seem better suited, for example in the following form. '
          },
          {type: ParagraphType.Equation, content:
              '\\mathbf{x}(t+1) = \\mathbf{x}(t) + ' +
              '\\sum_{j=0}^{t} \\sum_{\\text{other vortices } i}{ \\mathbf{d}_i(j) \\cdot \\frac' +
              '{\\text{intensity}_i \\cdot \\text{range}_i} ' +
              '{ \\lVert \\mathbf{d}_i(j) \\rVert^3 } } '
          },
          {type: ParagraphType.Paragraph, content:
              'The evolution of vortex positions is summarized ' +
              'in the equation above by putting together ' +
              'Newton\'s second law of motion and Newton\'s law of universal gravitation, ' +
              'approximated using the simple Euler ' +
              'method with time-steps of duration 1. ' +
              'Gravitation is made repulsive by using the appropriate convention ' +
              'for the orientation of d; in this case, it should be oriented from ' +
              'the vortex <i>i</i> to the vortex whose position is being updated. '
          },
          {type: ParagraphType.Paragraph, content:
              'Repulsion is also necessary at the border to prevent ' +
              'all the vortices from flying away. ' +
              'Besides, to avoid a weird resonance problem that would deserve a ' +
              'full technical article, ' +
              'near the border clockwise vortices are forced to move around the domain ' +
              'in a clockwise fashion; inversely for counter-clockwise ones. '
          },

          {type: ParagraphType.Title, content: 'V. User interaction'},
          {type: ParagraphType.Paragraph, content:
              'Why bother working with unsteady fields ' +
              'since they require additional computations? ' +
              'The essential characteristic of such vector fields is that they evolve throughout time; therefore, ' +
              'they can be interacted with by the beholder, allowing for user interaction.'
          },
          {type: ParagraphType.Paragraph, content:
              'In the proposed example, two simple actions are possible. ' +
              'The cursor is linked with a strongly repulsive virtual vortex, ' +
              'so that simply moving the mouse around moves everything away ' +
              'from the cursor. In the newly available free space, ' +
              'the user may right-click to form a new clockwise vortex, or ' +
              'left-click to form a counter-clockwise one. Holding the ' +
              'click shall make the vortex grow in intensity and range. '
          },

          {type: ParagraphType.Title, content: 'VI. Canvas: the decay hack'},
          {type: ParagraphType.Paragraph, content:
              'The art of Graphics ' +
              'carries a long tradition of clever hacks. ' +
              'The following one is quite simple and may not deserve to be called a "hack", but ' +
              'is still quite interesting. ' +
              'HTML\'s Canvas ships functions that allow to draw lines: ' +
              '"moveTo", which sort of moves the virtual pencil Canvas draws with, ' +
              'and "lineTo", which effectively draws the line from the previous pencil location. ' +
              'When all the lines in a frame have been drawn, and the frame has been rendered, ' +
              'there is no function to get back whatever was drawn then, so no way to quickly apply ' +
              'opacity on lines that would be ready and waiting, so to speak. ' +
              'The idea then instead of expensively softening all trails ' +
              'is to just draw a white rectangle with low opacity on the full Canvas so that ' +
              'all previously rendered segments progressively disappear as new frames are drawn. '
          }
        ]
      },

      {
        title: 'Spearman\'s correlation for dummies',
        author: 'm.s',
        date: '2019/01/10',
        body: [
          {type: ParagraphType.Title, content: 'I. Context'},
          {type: ParagraphType.Paragraph, content:
              'This article is ' +
              'about two supposedly equivalent formulations of ' +
              'a rank correlation coefficient, ' +
              '<a href="https://en.wikipedia.org/wiki/Spearman%27' +
              's_rank_correlation_coefficient">Spearman\'s rho</a>. ' +
              'The claim is as follows: '
          },
          {type: ParagraphType.Equation, content:
              '\\frac{\\sum_i(x_i-\\bar x)(y_i-\\bar y)}{\\sqrt{\\sum_i(x_i-\\bar x)^2 \\sum_i(y_i-\\bar y)^2}} = ' +
              '1 - \\frac{6 \\sum_i(y_i-x_i)^2}{n(n^2-1)}'
          },
          {type: ParagraphType.Paragraph, content:
              'This is apparently quite well-known in statistics, to the point that ' +
              'the right handside deserves to be called a popular formula. ' +
              'The purpose of this article is to offer a bit of context to it, ' +
              'unroll the demonstration step by step in a very detailed manner, ' +
              'review some basic statistics, and test equation rendering on this blog. '
          },
          {type: ParagraphType.Title, content: 'II. Rank correlation'},
          {type: ParagraphType.Paragraph, content:
              'Spearman\'s rho measures the similarity between two ' +
              'rankings. When <i>x</i> and <i>y</i> are ranking variables, ' +
              'that is, two lists of <i>n</i> elements ' +
              'where the <i>i</i><sup> th</sup> element gives the rank of a specific ' +
              'entity, rho is the ' +
              '<a href="https://en.wikipedia.org/wiki/Pearson_correlation_coefficient">' +
              'bivariate correlation</a> between <i>x</i> and <i>y</i>. ' +
              'In other words, it is the covariance of <i>x</i> and <i>y</i> ' +
              'divided by the product of their standard deviation. '
          },
          {type: ParagraphType.Equation, content:
              '\\rho = \\frac{\\text{cov}(x,y)}{\\sigma(x)\\sigma(y)} '
          },
          {type: ParagraphType.Paragraph, content:
              'By definition, the standard deviation of a variable is ' +
              'the square root of its variance, which is the ' +
              'expected square of the deviation between the variable and its expected value. '
          },
          {type: ParagraphType.Equation, content:
              '\\sigma(x) = \\sqrt{ \\mathbf{E}[(x - \\mathbf{E}[x])^2] }'
          },
          {type: ParagraphType.Paragraph, content:
              'By definition, the covariance of two variables is ' +
              'the expected product of their deviation from their expected values. '
          },
          {type: ParagraphType.Equation, content:
              '\\text{cov}(x,y) = \\mathbf{E}[(x - \\mathbf{E}[x])(y - \\mathbf{E}[y])]'
          },
          {type: ParagraphType.Paragraph, content:
              'In statistics, the expectation of a variable hints at its most representative value. ' +
              'In a nutshell, it is the probability-weighted average of ' +
              'all possible values the variable could have. Here the bar notation represents ' +
              'the average. '
          },
          {type: ParagraphType.Equation, content:
              '\\mathbf{E}(x) = \\bar x'
          },
          {type: ParagraphType.Paragraph, content:
              'Summing up: '
          },
          {type: ParagraphType.Equation, content:
              '\\rho = \\frac{ \\mathbf{E}[(x - \\bar x)(y - \\bar y)] }' +
              '{ \\sqrt{ \\mathbf{E}[(x - \\bar x)^2] }  \\sqrt{ \\mathbf{E}[(y - \\bar y)^2] } } '
          },
          {type: ParagraphType.Paragraph, content:
              'The expected value of a variable is just its probability-weighted average, so, ' +
              'taking <i>i</i> ranging from 1 to <i>n</i> for indexing possible values of <i>x</i> and <i>y</i>, ' +
              'numerator and denominator are computed as follows: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              '\\mathbf{E}[(x - \\bar x)(y - \\bar y)] = \\frac{1}{n^2} \\sum_i(x_i-\\bar x)(y_i-\\bar y) \\\\[1em]' +
              '\\sqrt{ \\mathbf{E}[(x - \\bar x)^2] }  \\sqrt{ \\mathbf{E}[(y - \\bar y)^2] } = ' +
              '\\sqrt{ \\frac{1}{n^2} \\sum_i(x_i-\\bar x)^2 } \\sqrt{ \\frac{1}{n^2} \\sum_i(y_i-\\bar y)^2 } \\\\[1em]  ' +
              '= \\frac{1}{n^2} \\sqrt{  \\sum_i(x_i-\\bar x)^2 \\sum_i(y_i-\\bar y)^2 } \\\\[0.5em]' +
              ' '
          },
          {type: ParagraphType.Paragraph, content:
              'As factors cancel out, we are left with the following formula that ' +
              'will go through a bit of refactoring in the next section: '
          },
          {type: ParagraphType.Equation, content:
              '\\rho = \\frac{\\sum_i(x_i-\\bar x)(y_i-\\bar y)}{\\sqrt{\\sum_i(x_i-\\bar x)^2 \\sum_i(y_i-\\bar y)^2}} '
          },
          {type: ParagraphType.Title, content: 'III. Ranks without ties: detailed reformulation'},
          {type: ParagraphType.Paragraph, content:
              'Keep in mind, we are working with two variables that represent the ' +
              'ranking of some fixed collection of entities. ' +
              'Assuming there are no ties in either ranking, Spearman\'s rho can be simplified. ' +
              'First thing to notice is how the means are constant: '
          },
          {type: ParagraphType.Equation, content:
              ' \\bar x = \\bar y = \\frac{n+1}{2}'
          },
          {type: ParagraphType.Paragraph, content:
              'Looking at the denominator, it must also be constant. ' +
              'Notice how just rearranging the way variables are summed in the denominator ' +
              'does not change the value of the sum. '
          },
          {type: ParagraphType.Equation, content:
              '\\sum_i(x_i-\\bar x)^2 = \\sum_i(y_i-\\bar y)^2 = \\sum_i(i-\\frac{n+1}{2})^2 '
          },
          {type: ParagraphType.Paragraph, content:
              'That way, the denominator is just: '
          },
          {type: ParagraphType.Equation, content:
              '\\sqrt{\\sum_i(x_i-\\bar x)^2 \\sum_i(y_i-\\bar y)^2} = \\sum_i(x_i-\\bar x)^2 '
          },
          {type: ParagraphType.Paragraph, content:
              'At this point, since one is interested in the value of this multiplicative ' +
              'constant, it seems there is little choice but to actually do some computation. ' +
              'So, distributing, splitting sums and factorizing: '
          },
          {type: ParagraphType.Equation, content:
              ' \\\\' +
              '\\sum_i(x_i-\\bar x)^2 = \\sum_i(x_i^2 - 2 x_i\\bar x + \\bar x^2) \\\\[1em]' +
              '= \\sum_ix_i^2 - 2 \\bar x \\sum_ix_i + \\bar x^2 \\sum_i 1 \\\\[1em]' +
              '= \\sum_ii^2 - 2 \\frac{n+1}{2} \\sum_ii + (\\frac{n+1}{2})^2 \\sum_i 1 \\\\[1em]' +
              '= \\frac{n(n+1)(2n+1)}{6} - (n+1) \\frac{n(n+1)}{2} + (\\frac{n+1}{2})^2n \\\\[1em]' +
              '= \\frac{n(n+1)}{2} ( \\frac{1}{3}(2n+1) - (n+1) + \\frac{1}{2}(n+1) ) \\\\[1em]' +
              '= \\frac{n(n+1)}{12} ( 2(2n+1) - 3(n+1) ) \\\\[1em]' +
              '= \\frac{n(n+1)}{12} ( 4n+2 - 3n-3) ) \\\\[1em]' +
              '= \\frac{n(n+1)}{12} ( n-1 ) \\\\[1em]' +
              '= \\frac{n(n^2-1)}{12}\\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'Now looking at the numerator, distributing the product should yield three constant ' +
              'terms and another one, a product between <i>x</i> and <i>y</i>, which the original ' +
              'question asked to ' +
              'express in terms of their difference. '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              '\\sum_i(x_i-\\bar x)(y_i-\\bar y) = \\sum_i(x_iy_i-\\bar yx_i-\\bar xy_i+\\bar x\\bar y) \\\\[1em]' +
              '= C_1 + \\sum_i(x_iy_i) \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'The constant terms are just an offset, ' +
              'they should not change the correlation measure whether the input ' +
              'is translated or scaled. ' +
              'Remark that the product can be simply expressed from the difference. '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              '\\sum_i(x_i-y_i)^2 = \\sum_i(x_i^2) + \\sum_i(y_i^2) - 2\\sum_i(x_iy_i) \\\\[1em] ' +
              '\\sum_i(x_iy_i) = C_2 - \\frac{1}{2}\\sum_i(x_i-y_i)^2  \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'Plugging everything into rho yields: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              '\\rho ' +
              '= \\frac{\\sum_i(x_i-\\bar x)(y_i-\\bar y)}{\\sum_i(x_i-\\bar x)^2}' +
              '\\\\[1em]' +
              '\\rho = \\frac{12}{n(n^2-1)} (C_1+C_2-\\frac{1}{2}\\sum_i(x_i-y_i)^2) \\\\[1em]' +
              '\\rho = C_3 - \\frac{6\\sum_i(x_i-y_i)^2}{n(n^2-1)} \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'No real computation is needed to find the last constant:'
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              'C_3 =  \\frac{1}{\\sum_i(x_i-\\bar x)^2} ' +
              '\\sum_i(\\frac{1}{2}(x_i^2+y_i^2) - x_i\\bar y - y_i\\bar x + \\bar x\\bar y) \\\\[1em]' +
              '= \\frac{1}{\\sum_i(x_i-\\bar x)^2} \\sum_i(x_i^2 - 2x_i\\bar x + \\bar x^2) \\\\[1em]' +
              '= 1 \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Title, content: 'IV. Digression: remarkable integer sums'},
          {type: ParagraphType.Paragraph, content:
              'Just a quick note here: the following may sound elementary ' +
              'but it proves quite challenging in practice to explain ' +
              'algebraically to people with little mathematical background, ' +
              'because raw algebra lacks the intuitive nature of, say, geometry. ' +
              'Staying in the context of algebra, it is good to remember that: '
          },
          {type: ParagraphType.Quotation, content:
              '(...) mathematics is the art of giving the same name to different things.',
            origin: 'H. Poincaré',
            source: 'The Future of Mathematics'
          },
          {type: ParagraphType.Paragraph, content:
              'Sum, definition: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              '\\sum^n(a) = \\underbrace{a + ... + a}_{n \\text{ times}} \\\\[2em]' +
              '= n\\times a \\\\[1em]' +
              '= na \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'Simple distributivity, an example demonstration: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              'n(a+b) = \\sum^n(a+b) \\\\[1em]' +
              '= \\sum^na + \\sum^nb \\\\[1em]' +
              '= na + nb \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'The sum of ones: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              'S_0 = \\sum_i^n i^0 = \\sum_i^n 1 = n \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'The sum of integers: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              'S_1 = \\sum_i^n i^1 \\\\[1em]' +
              '= \\sum_{i=1}^{\\lceil n/2 \\rceil}(i) + \\sum_{i=1}^{\\lceil n/2 \\rceil}(n+1-i) - ' +
              '(n+1)(n \\text{ mod } 2)' +
              '\\\\[1em]' +
              '= \\sum_{i=1}^{\\lceil n/2 \\rceil}(n+1) - (n+1)(n \\text{ mod } 2) \\\\[1em]' +
              '= (n+1)\\lceil n/2 \\rceil - (n+1)(n \\text{ mod } 2) \\\\[1em]' +
              '= (n+1)(\\lceil n/2 \\rceil - n \\text{ mod } 2) \\\\[1em]' +
              '= \\frac{n(n+1)}{2} \\\\[1em]' +
              ''
          },
          {type: ParagraphType.Paragraph, content:
              'The sum of squares: '
          },
          {type: ParagraphType.Equation, content:
              '\\\\' +
              'S_2 = \\sum_i^n i^2 \\\\[1em]' +
              '\\sum_i^n(i+1)^3 = \\sum_i^n(i^3+3i^2+3i+1) \\\\[1em]' +
              '\\sum_i^n(i+1)^3 - \\sum_i^ni^3 = \\sum_i^n(3i^2)+\\sum_i^n(3i)+\\sum_i^n(1) \\\\[1em]' +
              '(n+1)^3-1 = 3S_2 + 3\\sum_i^n(i) + \\sum_i^n(1) \\\\[1em]' +
              'S_2 =\\frac{1}{3}((n+1)^3 - 3\\sum_i^n(i) - \\sum_i^n(1)-1) \\\\[1em]' +
              '=\\frac{1}{3}((n+1)^3 - 3\\frac{n(n+1)}{2} - n-1) \\\\[1em]' +
              '=\\frac{1}{3}(\\frac{2}{2}(n+1)^3 - \\frac{3}{2}(n+1)n - \\frac{2}{2}(n+1)) \\\\[1em]' +
              '=\\frac{1}{6}(n+1)(2(n+1)^2 - 3n - 2) \\\\[1em]' +
              '=\\frac{1}{6}(n+1)(2n^2 + 4n + 2 - 3n - 2) \\\\[1em]' +
              '=\\frac{1}{6}(n+1)(2n^2 + n) \\\\[1em]' +
              '= \\frac{n(n+1)(2n+1)}{6} \\\\[1em]' +
              ''
          }
        ],
        validated: true
      },
      // {
      //   title: 'Example code',
      //   author: 'm.s',
      //   date: '2019/02/24',
      //   body: [
      //     {type: ParagraphType.Title, content: 'Introduction'},
      //     {type: ParagraphType.Paragraph, content:
      //         'This is just an example article to remember ' +
      //         'how to include code and accordion code.'
      //     },
      //     {type: ParagraphType.Title, content: 'Code'},
      //     {type: ParagraphType.Code, language: 'javascript',
      //       content:
      //         '$=_=>`$=${$};$()`;$()\n' +
      //         '(_=$=>`(_=${_})()`)()'
      //     },
      //     {type: ParagraphType.Title, content: 'Collapsible code'},
      //     {type: ParagraphType.CollapsibleCode, language: 'javascript',
      //       heading: 'JS fbomb ',
      //       content:
      //         '(function f() {\n' +
      //         '\trequire(\'child_process\')\n' +
      //         '\t\t.spawn(process.argv[0], [\'-e\', \'(\' + f.toString() + \'());\']);\n' +
      //         '\trequire(\'child_process\')\n' +
      //         '\t\t.spawn(process.argv[0], [\'-e\', \'(\' + f.toString() + \'());\']); \n' +
      //         '}\n' +
      //         '\/\/ Please don\'t do that.\n' +
      //         '\/\/()\n' +
      //         ');\n'
      //     }
      //   ]
      // }
    ];

    for (let a = 0; a < articles.length; ++a) {
      articles[a]['type'] = 'technical';
    }

    return articles;
  }
}
